### ISSUE TITLE
Shapes attribute is not considered when running `Validate`

### ISSUE THREAD

**Issue by jo-fra** [elsevierlabs-os/linked-data#12]
Linked Data Extension v1.0.6
VSCode/Windows Version:
![image](https://github.com/elsevierlabs-os/linked-data/assets/69941576/47539737-d472-4414-a7c3-413bfba82d6b)

I am using your example for SHACL validation by placing the shapes attribute as a comment with the relative path to the shapes file:
```ttl
# shapes: shacl_example_shapes.ttl
@prefix ex: <https://example.com/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:Alice
	a ex:Person ;
	ex:ssn "987-65-432A" .
```

However, still a dialog opens asking me to select the shapes file.

**Comment by jo-fra** [comment]
It seems to be an issue with line endings. It's working if I change line endings from `CRLF` to `LF`.

**Comment by RinkeHoekstra** [comment]
Thanks! I've fixed the regex to also allow for an optional `\r`. This should now work for CRLF too.
