### ISSUE TITLE
Queries not handling sparse data well

### ISSUE THREAD

**Issue by lloyd-jackman-thomsonreuters** [elsevierlabs-os/linked-data#15]
Hello

I have noticed that when using a TTL to query with optional where clauses, the output doesn't allow for blank values and therefore shifts the populated values of one column into the unpopulated value.

For example, if I run the below query:
```
# file: example_file.ttl

prefix ex: <http://www.example.com>

select ?Name ?City ?PhoneNumber ?DateOfBirth
where {
?Name ex:LivesIn ?City.
?Name ex:BornOn ?DateOfBirth.
optional {?Name ex:HasPhoneNumber ?PhoneNumber.}
}
```

And my data has incomplete phone numbers and hence is being queried as an optional data point, I am seeing something like the below returned:

| Name  	| City       	| PhoneNumber  	| DateOfBirth 	|
|-------	|------------	|--------------	|-------------	|
| Fred  	| London     	| 1996-01-02   	|             	|
| Dave  	| Manchester 	| +44123456789 	| 1985-12-13  	|
| Sarah 	| Cardiff    	| 1992-10-30   	|             	|

The lack of phone number for Fred and Sarah sees their dates of birth slip into the phone number column.

I would expect it to look like the below:

| Name  	| City       	| PhoneNumber  	| DateOfBirth 	|
|-------	|------------	|--------------	|-------------	|
| Fred  	| London     	|              	| 1996-01-02  	|
| Dave  	| Manchester 	| +44123456789 	| 1985-12-13  	|
| Sarah 	| Cardiff    	|              	| 1992-10-30  	|

This appears on both the CSV output and the HTML view.

**Comment by RinkeHoekstra** [comment]
Thanks for flagging this @lloyd-jackman-thomsonreuters !

**Comment by lloyd-jackman-thomsonreuters** [comment]
CORPORATE

Many thanks for fixing it, great work!


Lloyd Jackman

Product Owner, DaaS Data Pipeline

London Stock Exchange Group



***@***.******@***.***>



lseg.com



[wPvoEp5tmbNFAAAAABJRU5ErkJggg==]



***@***.***?anonymous&ep=signature>             Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________
