### ISSUE TITLE
feature: syntax highlight `.acl` files

### ISSUE THREAD

**Issue by jeswr** [elsevierlabs-os/linked-data#3]
Thanks for this great tool!

In the context of [solid](https://solidproject.org/) we often have RDF serialized `.acl` files. Specifically they usually serialised in turtle. Could this extension add support to apply syntax highlighting to those files by default if there is no other syntax highlighting already applied to `.acl` by other extensions.

**Comment by RinkeHoekstra** [comment]
Hi @jeswr that's an interesting suggestion. I never use `.acl` files myself, are they always in Turtle?

In principle, the syntax highlighting is supported through the [Stardog Languages Expansion Pack](https://marketplace.visualstudio.com/items?itemName=stardog-union.vscode-stardog-languages). Perhaps the best way to add the `.acl` file extension is in that `package.json` file, here:

https://github.com/stardog-union/stardog-vsc/blob/39ded13460627a45154b22eaa84baaf59b032f3d/stardog-rdf-grammars/package.json#L56

We could try to override that definition in the `package.json` for this extension, but I'd have to look into whether that's even possible.

**Comment by jeswr** [comment]
Not necessarily (the Solid spec requires support for both turtle and json-ld) - but every `.acl` I've seen to date has been in turtle so its a pretty good heuristic :wink: .

> In principle, the syntax highlighting is supported through the [Stardog Languages Expansion Pack](https://marketplace.visualstudio.com/items?itemName=stardog-union.vscode-stardog-languages). Perhaps the best way to add the .acl file extension is in that package.json file, here:

Great! I'll create an issue & PR over there :)
