### ISSUE TITLE
Error when running Validate

### ISSUE THREAD

**Issue by mielvds** [elsevierlabs-os/linked-data#5]
The SHACL graph get loaded fine, but I get:

`this.dataset.match is not a function`

Any ideas?

**Comment by forsakendaemon** [comment]
I'm getting this same error on pretty much anything that I try and run Validate on - the graphs are parsed, but the error pops up after that. I'm digging into it at the moment and will update this thread if I find any likely culprits!

**Comment by forsakendaemon** [comment]
By going through the SHACL file that I was using, this seems to come up when using `<http://www.w3.org/ns/shacl#targetSubjectsOf>`. I have to run off today so I'm not yet sure where in the process the error is occurring and haven't yet put together a minimal example, but that might be a good place to start looking!

**Comment by RinkeHoekstra** [comment]
@forsakendaemon I'm closing this one... sorry for being not very responsive. Let me know if you still want to discuss!
