### ISSUE TITLE
Release extension on openvsx marketplace

### ISSUE THREAD

**Issue by jeswr** [elsevierlabs-os/linked-data#6]
In order to support this extension vscodium editors (that have the telemetry from vscode stripped) it needs to be published to the [openvsx](https://www.gitpod.io/blog/open-vsx) marketplace.

I would be very grateful if this could be supported (and this has also been requested in https://forum.solidproject.org/t/solid-app-development-tech-tools-stack-recommentation/5838/7).

**Comment by jeswr** [comment]
bump @RinkeHoekstra

**Comment by RinkeHoekstra** [comment]
This is doable, yes. I'll try to remember doing that for the next release.

**Comment by RinkeHoekstra** [comment]
@jeswr Apologies, but it turns out to be trickier than I expected as I have to juggle legal agreements. This is not something I particularly enjoy doing, as you may understand.
