### ISSUE TITLE
Dark Mode support for Visualizations please??

### ISSUE THREAD

**Issue by tduval-unifylogic** [elsevierlabs-os/linked-data#8]
Hi!

Just discovered your extension and really like its capabilities.
Could you please provide an update to detect whether or not dark-mode is set and invert the colors of the labels in the visualization so we can read them?

Thanks!

[tduval-unifylogic](https://github.com/tduval-unifylogic)
<img width="670" alt="image" src="https://user-images.githubusercontent.com/62360524/211856782-cf17fac5-0699-4678-8f98-bb8196821d7d.png">

**Comment by RinkeHoekstra** [comment]
Ooh, good one. That should be doable.

**Comment by RinkeHoekstra** [comment]
The new visualisation introduced last year was already much more readable, but I've just tweaked the CSS to take the theme into account. It's better now... not perfect, but better.
